### ISSUE TITLE
長めのリストを更新すると QUOTA_BYTES_PER_ITEM quota exceeded が出てしまう

### ISSUE THREAD

**Issue by kt81** [retrorocket/github-name-alias-chrome-extension#1]
手元の長大なリストを食わせたところ、成功した風なのに更新されていないという事象が起きました。
コンソールを確認したところ、掲題の通り `QUOTA_BYTES_PER_ITEM quota exceeded` が出ているようです。

ひとまず私の用途だとストレージを local にして無制限書き込みができるならそれで問題ないんじゃないかなと思っています。

素晴らしい拡張を作成してくださったことを感謝します

**Comment by retrorocket** [comment]
@kt81
ご利用いただきありがとうございます。また、事象の報告についても誠にありがとうございます。

> 成功した風なのに更新されていないという事象

- ご指摘の通り、`chrome.storage.sync`では 8kb を超えるとデータが保存できないため、保存に失敗した場合はエラーを出すようにしました。( #2 )
- `chrome.storage.local` についてですが、8kb を超える登録はエッジケースであると考えており、また、開発作業時は`chrome.storage.sync` できないと困る場面が多いため、今のところ対応する予定はありません。

> ひとまず私の用途だとストレージを local にして無制限書き込みができるならそれで問題ないんじゃないかなと思っています。

ご記載の方法で動くと思いますので、必要であればご自身で修正の上、デベロッパーモードで使用していただければ幸いです。お手数をおかけして申し訳ありません。

要望が多ければ local か sync か選べるようにするかもしれません。
余談ですが、このスクリプトについてはものすごい突貫で作っていて中身がむちゃくちゃなので、対応する際は全部書き直すことになりそうです。

**Comment by kt81** [comment]
@retrorocket 
エラー表示のご対応ありがとうございます。また、フォークで対応すべしとの旨承知しましたｍｍ
